admin_login:
    pattern:   /login
    defaults:  { _controller: MuseuBackendBundle:Default:login }

admin_login_check:
    pattern:   /login_check

admin_logout:
    path:   /logout

museu_backend_homepage:
    pattern:  /
    defaults: { _controller: MuseuBackendBundle:Default:index }

MuseuBackendBundle_banner:
        resource: "@MuseuBackendBundle/Resources/config/routing/banner.yml"
        prefix:   /banner

MuseuBackendBundle_exposicoes:
        resource: "@MuseuBackendBundle/Resources/config/routing/exposition.yml"
        prefix:   /exposicoes

MuseuBackendBundle_imprensa:
        resource: "@MuseuBackendBundle/Resources/config/routing/press.yml"
        prefix:   /imprensa

MuseuBackendBundle_livros:
        resource: "@MuseuBackendBundle/Resources/config/routing/book.yml"
        prefix:   /livros

MuseuBackendBundle_ebooks:
        resource: "@MuseuBackendBundle/Resources/config/routing/ebook.yml"
        prefix:   /ebooks

MuseuBackendBundle_collection:
        resource: "@MuseuBackendBundle/Resources/config/routing/collection.yml"
        prefix:   /acervo

MuseuBackendBundle_music:
        resource: "@MuseuBackendBundle/Resources/config/routing/music.yml"
        prefix:   /music

MuseuBackendBundle_videoacervo:
        resource: "@MuseuBackendBundle/Resources/config/routing/videoacervo.yml"
        prefix:   /videoacervo

museu_backend_upload:
    pattern:  /upload
    defaults: { _controller: MuseuBackendBundle:Default:index }

MuseuBackendBundle_tese:
        resource: "@MuseuBackendBundle/Resources/config/routing/tese.yml"
        prefix:   /tese

MuseuBackendBundle_statement:
        resource: "@MuseuBackendBundle/Resources/config/routing/statement.yml"
        prefix:   /depoimentos

MuseuBackendBundle_timeline:
        resource: "@MuseuBackendBundle/Resources/config/routing/timeline.yml"
        prefix:   /linhadotempo

MuseuBackendBundle_video:
        resource: "@MuseuBackendBundle/Resources/config/routing/video.yml"
        prefix:   /video

MuseuBackendBundle_newsletter:
        resource: "@MuseuBackendBundle/Resources/config/routing/newsletter.yml"
        prefix:   /newsletter

MuseuBackendBundle_picfooter:
        resource: "@MuseuBackendBundle/Resources/config/routing/picfooter.yml"
        prefix:   /imgfooter