museu_backend_homepage:
    pattern:  /
    defaults: { _controller: MuseuBackendBundle:Default:index }

MuseuBackendBundle_banner:
        resource: "@MuseuBackendBundle/Resources/config/routing/banner.yml"
        prefix:   /banner

MuseuBackendBundle_exposicoes:
        resource: "@MuseuBackendBundle/Resources/config/routing/exposition.yml"
        prefix:   /exposicoes

MuseuBackendBundle_imprensa:
        resource: "@MuseuBackendBundle/Resources/config/routing/press.yml"
        prefix:   /imprensa

MuseuBackendBundle_livros:
        resource: "@MuseuBackendBundle/Resources/config/routing/book.yml"
        prefix:   /livros