CREATE TABLE AdminUser (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, isActive TINYINT(1) NOT NULL, creaeted_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Banner (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
ALTER TABLE Banner ADD pic VARCHAR(255) DEFAULT NULL
CREATE TABLE exposition (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, date DATETIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE expositon_image (id INT AUTO_INCREMENT NOT NULL, exposition_id INT NOT NULL, pic VARCHAR(255) NOT NULL, INDEX IDX_54969F5F88ED476F (exposition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE expositon_image ADD CONSTRAINT FK_54969F5F88ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id)
ALTER TABLE exposition CHANGE date date DATE NOT NULL
CREATE TABLE ExpositionAuthor (id INT AUTO_INCREMENT NOT NULL, exposition_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_1C09DAEA88ED476F (exposition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE ExpositionAuthor ADD CONSTRAINT FK_1C09DAEA88ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id);
ALTER TABLE exposition ADD subtitle VARCHAR(255) NOT NULL
ALTER TABLE expositon_image ADD title VARCHAR(255) NOT NULL, ADD author VARCHAR(255) NOT NULL
ALTER TABLE expositon_image CHANGE exposition_id exposition_id INT DEFAULT NULL
ALTER TABLE ExpositionAuthor CHANGE exposition_id exposition_id INT DEFAULT NULL
CREATE TABLE exposition_author (id INT AUTO_INCREMENT NOT NULL, exposition_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_7043D3CB88ED476F (exposition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE exposition_image (id INT AUTO_INCREMENT NOT NULL, exposition_id INT DEFAULT NULL, pic VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, INDEX IDX_FE3094AA88ED476F (exposition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE exposition_author ADD CONSTRAINT FK_7043D3CB88ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id);
ALTER TABLE exposition_image ADD CONSTRAINT FK_FE3094AA88ED476F FOREIGN KEY (exposition_id) REFERENCES exposition (id)
ALTER TABLE exposition_author CHANGE exposition_id exposition_id INT NOT NULL;
ALTER TABLE exposition_image CHANGE exposition_id exposition_id INT NOT NULL
ALTER TABLE exposition_author CHANGE exposition_id exposition_id INT NOT NULL;
ALTER TABLE exposition_image CHANGE exposition_id exposition_id INT NOT NULL
ALTER TABLE exposition_image ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME NOT NULL
