collection:
    path:     /
    defaults: { _controller: "MuseuBackendBundle:Collection:index" }

collection_show:
    path:     /{id}/show
    defaults: { _controller: "MuseuBackendBundle:Collection:show" }

collection_new:
    path:     /new
    defaults: { _controller: "MuseuBackendBundle:Collection:new" }

collection_create:
    path:     /create
    defaults: { _controller: "MuseuBackendBundle:Collection:create" }
    requirements: { _method: post }

collection_edit:
    path:     /{id}/edit
    defaults: { _controller: "MuseuBackendBundle:Collection:edit" }

collection_update:
    path:     /{id}/update
    defaults: { _controller: "MuseuBackendBundle:Collection:update" }
    requirements: { _method: post|put }

collection_delete:
    path:     /{id}/delete
    defaults: { _controller: "MuseuBackendBundle:Collection:delete" }
    requirements: { _method: post|delete }
