ebooks:
    pattern:  /
    defaults: { _controller: "MuseuBackendBundle:eBook:index" }

ebooks_show:
    pattern:  /{id}/show
    defaults: { _controller: "MuseuBackendBundle:eBook:show" }

ebooks_new:
    pattern:  /new
    defaults: { _controller: "MuseuBackendBundle:eBook:new" }

ebooks_create:
    pattern:  /create
    defaults: { _controller: "MuseuBackendBundle:eBook:create" }
    requirements: { _method: post }

ebooks_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MuseuBackendBundle:eBook:edit" }

ebooks_update:
    pattern:  /{id}/update
    defaults: { _controller: "MuseuBackendBundle:eBook:update" }
    requirements: { _method: post|put }

ebooks_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MuseuBackendBundle:eBook:delete" }
    requirements: { _method: post|delete }
