music:
    path:     /
    defaults: { _controller: "MuseuBackendBundle:Music:index" }

music_show:
    path:     /{id}/show
    defaults: { _controller: "MuseuBackendBundle:Music:show" }

music_new:
    path:     /new
    defaults: { _controller: "MuseuBackendBundle:Music:new" }

music_create:
    path:     /create
    defaults: { _controller: "MuseuBackendBundle:Music:create" }
    requirements: { _method: post }

music_edit:
    path:     /{id}/edit
    defaults: { _controller: "MuseuBackendBundle:Music:edit" }

music_update:
    path:     /{id}/update
    defaults: { _controller: "MuseuBackendBundle:Music:update" }
    requirements: { _method: post|put }

music_delete:
    path:     /{id}/delete
    defaults: { _controller: "MuseuBackendBundle:Music:delete" }
    requirements: { _method: post|delete }
