newsletter:
    path:     /
    defaults: { _controller: "MuseuBackendBundle:Newsletter:index" }

newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "MuseuBackendBundle:Newsletter:show" }

newsletter_new:
    path:     /new
    defaults: { _controller: "MuseuBackendBundle:Newsletter:new" }

newsletter_create:
    path:     /create
    defaults: { _controller: "MuseuBackendBundle:Newsletter:create" }
    requirements: { _method: post }

#newsletter_create_front:
#    path:     /inscrever
#    defaults: { _controller: "MuseuBackendBundle:Newsletter:createFront" }
#    requirements: { _method: post }

newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "MuseuBackendBundle:Newsletter:edit" }

newsletter_update:
    path:     /{id}/update
    defaults: { _controller: "MuseuBackendBundle:Newsletter:update" }
    requirements: { _method: post|put }

newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "MuseuBackendBundle:Newsletter:delete" }
    requirements: { _method: post|delete }
