timeline:
    path:     /
    defaults: { _controller: "MuseuBackendBundle:Timeline:index" }

timeline_show:
    path:     /{id}/show
    defaults: { _controller: "MuseuBackendBundle:Timeline:show" }

timeline_new:
    path:     /new
    defaults: { _controller: "MuseuBackendBundle:Timeline:new" }

timeline_create:
    path:     /create
    defaults: { _controller: "MuseuBackendBundle:Timeline:create" }
    requirements: { _method: post }

timeline_edit:
    path:     /{id}/edit
    defaults: { _controller: "MuseuBackendBundle:Timeline:edit" }

timeline_update:
    path:     /{id}/update
    defaults: { _controller: "MuseuBackendBundle:Timeline:update" }
    requirements: { _method: post|put }

timeline_delete:
    path:     /{id}/delete
    defaults: { _controller: "MuseuBackendBundle:Timeline:delete" }
    requirements: { _method: post|delete }
