museu_frontend_homepage:
    pattern:  /
    defaults: { _controller: MuseuFrontendBundle:Default:index }


museu_oque:
    pattern:   /o-que-e
    defaults:  { _controller: MuseuFrontendBundle:Default:Oque }

museu_equipe:
    pattern:   /equipe
    defaults:  { _controller: MuseuFrontendBundle:Default:equipe }

museu_localizacao:
    pattern:   /localizacao
    defaults:  { _controller: MuseuFrontendBundle:Default:localizacao }

museu_missao:
    pattern:   /missao
    defaults:  { _controller: MuseuFrontendBundle:Default:missao }

museu_educacao:
    pattern:   /educacao
    defaults:  { _controller: MuseuFrontendBundle:Default:educacao }

museu_imprensa:
    pattern:   /sala-de-imprensa
    defaults:  { _controller: MuseuFrontendBundle:Default:press }

museu_publicacoes:
    pattern:   /publicacoes
    defaults:  { _controller: MuseuFrontendBundle:Default:publications }

museu_livros:
    pattern:   /publicacoes/livros
    defaults:  { _controller: MuseuFrontendBundle:Default:books }

museu_ebooks:
    pattern:   /publicacoes/ebooks
    defaults:  { _controller: MuseuFrontendBundle:Default:ebooks }

museu_videos:
    pattern:   /publicacoes/videos
    defaults:  { _controller: MuseuFrontendBundle:Default:videosAcervo }

museu_music:
    pattern:   /publicacoes/musicas
    defaults:  { _controller: MuseuFrontendBundle:Default:music }

museu_newsletter:
    pattern:   /newsletter
    defaults:  { _controller: MuseuFrontendBundle:Default:newsletter }

museu_teses:
    pattern:   /publicacoes/teses
    defaults:  { _controller: MuseuFrontendBundle:Default:teses }

museu_contato:
    pattern:   /contato
    defaults:  { _controller: MuseuFrontendBundle:Default:contact }

museu_acessibilidade:
    pattern:   /acessibilidade
    defaults:  { _controller: MuseuFrontendBundle:Default:acessibilidade }

museu_acervo:
    pattern:   /acervo-digitais/{option}
    defaults:  { _controller: MuseuFrontendBundle:Acervo:index, 'option': '' }

museu_view_acervo:
    pattern:   /acervo-digitais/ver/{id}
    defaults:  { _controller: MuseuFrontendBundle:Acervo:view }

#museu_acervo:
#    pattern:   /acervo-digitais/videos
#    defaults:  { _controller: MuseuFrontendBundle:Acervo:videos }

museu_guariba:
    pattern:   /guariba/{option}
    defaults:  { _controller: MuseuFrontendBundle:Default:guariba }

museu_guariba_map:
    pattern:   /guariba/mapa
    defaults:  { _controller: MuseuFrontendBundle:Default:guaribaMapa }

museu_guariba_timeline:
    pattern:   /guariba/linha-do-tempo
    defaults:  { _controller: MuseuFrontendBundle:Default:guaribaTimeline }

museu_tvmtc:
    pattern:   /tv-mtc
    defaults:  { _controller: MuseuFrontendBundle:Default:tv }

museu_radiomtc:
    pattern:   /radio-mtc
    defaults:  { _controller: MuseuFrontendBundle:Default:radio }

museu_cinemtc:
    pattern:   /cine-mtc
    defaults:  { _controller: MuseuFrontendBundle:Default:cine }

museu_universidade:
    pattern:   /universidade
    defaults:  { _controller: MuseuFrontendBundle:Default:universidade }

newsletter_create_front:
    path:     /newsletter/inscrever
    defaults: { _controller: "MuseuBackendBundle:Newsletter:createFront" }
    requirements: { _method: post }
