parameters:
#    museu_frontend.example.class: Museu\FrontendBundle\Example

services:
#    museu_frontend.example:
#        class: %museu_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
