parameters:
#    museu_frontend.example.class: Museu\FrontendBundle\Example

services:
#    museu_frontend.example:
#        class: %museu_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    your.own.twig.controller_action_extension:
        class: Museu\FrontendBundle\Twig\Extension\ControllerActionExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }